name: Deploy Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Restore authentication
        shell: bash
        run: |
          cat <<EOF > ~/.clasprc.json
${{ secrets.CLASPRC_JSON }}
EOF

      - name: Debug environment
        run: |
          echo "Current directory:"
          pwd

          echo "Files:"
          ls -la

          echo "Appsscript:"
          cat appsscript.json

          echo "Clasp version:"
          clasp -v

          echo "Clasp status:"
          clasp status

      - name: Push
        run: clasp push --force
